In [25]:
import pandas as pd

df = pd.read_csv('amazon_delivery.csv')
df

            Order_ID  Agent_Age  ...  Delivery_Time     Category
0      ialx566343618         37  ...            120     Clothing
1      akqg208421122         34  ...            165  Electronics
2      njpu434582536         23  ...            130       Sports
3      rjto796129700         38  ...            105    Cosmetics
4      zguw716275638         32  ...            150         Toys
...              ...        ...  ...            ...          ...
43734  jlxf819993117         30  ...            160         Home
43735  aevx342135787         21  ...            180      Jewelry
43736  xnek760674819         30  ...             80         Home
43737  cynl434665991         20  ...            130      Kitchen
43738  nsyz997960170         23  ...            180    Cosmetics

[43739 rows x 16 columns]

In [26]:
df = df.drop(['Order_ID', 'Pickup_Time'], axis=1)

In [27]:
import datetime as dt
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

df['day_of_week'] = df['Order_Date'].dt.dayofweek

df['is_weekend'] = (df['day_of_week'] >= 5).astype(int)

df['month'] = df['Order_Date'].dt.month

df['Order_Time'] = pd.to_datetime(df['Order_Time'], format= '%H:%M:%S', errors='coerce')

df['hour'] = df['Order_Time'].dt.hour

df['order_hour_block'] = pd.cut(df['hour'], bins=[0, 6, 12, 18, 24], labels=('night', 'morning', 'afternoon', 'evening'))

df['is_fast_delivery'] = (df['Delivery_Time'] >= df['Delivery_Time'].median()).astype(int)

## The columns 'Order_Date', and 'Date_time' served their purpose. Having successfuly extracted the needed information from those columns, I can drop them without hesitation.

In [28]:
df = df.drop(['Order_Date', 'Order_Time', 'hour', 'Delivery_Time'], axis=1)

In [29]:
df.head()

   Agent_Age  Agent_Rating  ...  order_hour_block  is_fast_delivery
0         37           4.9  ...           morning                 0
1         34           4.5  ...           evening                 1
2         23           4.4  ...           morning                 1
3         38           4.7  ...         afternoon                 0
4         32           4.6  ...         afternoon                 1

[5 rows x 16 columns]

In [30]:
df.nunique()

Agent_Age             22
Agent_Rating          28
Store_Latitude       521
Store_Longitude      415
Drop_Latitude       4367
Drop_Longitude      4367
Weather                6
Traffic                5
Vehicle                4
Area                   4
Category              16
day_of_week            7
is_weekend             2
month                  3
order_hour_block       3
is_fast_delivery       2
dtype: int64

In [31]:
onehot_cols =['Weather', 'Traffic', 'Vehicle', 'Area', 'order_hour_block']
target_cols = ['Category']

df.shape

(43739, 16)

In [32]:
from sklearn.model_selection import train_test_split

X = df.drop('is_fast_delivery', axis=1)
y = df['is_fast_delivery']


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [33]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, TargetEncoder

preprocessor = ColumnTransformer(transformers=[
    ('onehot', OneHotEncoder(), onehot_cols), 
    ('target', TargetEncoder(), target_cols)
], remainder='passthrough')

In [34]:
X_train_prepped = preprocessor.fit_transform(X_train, y_train)
X_test_prepped = preprocessor.transform(X_test)

In [35]:
X_train_prepped.shape

(34991, 34)

In [40]:
from xgboost import XGBClassifier

clf = XGBClassifier(random_state=42, n_jobs =-1)
clf.fit(X_train_prepped, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=-1, num_parallel_tree=None, ...)

In [41]:
train_score = clf.score(X_train_prepped, y_train)
test_score = clf.score(X_test_prepped, y_test)

print(f'train score: {train_score}')
print(f'test score: {test_score}')

train score: 0.9009745363093367
test score: 0.8211019661636946

In [42]:
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingRandomSearchCV

params = {
    'learning_rate': [0.01, 0.03, 0.05, 0.1],  
    'reg_lambda': [0, 2, 3, 5], 
    'reg_alpha': [0, 2, 3, 5], 
    'max_depth': [3, 5, 7]
}
boosted_clf = HalvingRandomSearchCV(
    estimator=clf,cv=5,verbose=2, param_distributions=params, 
)
boosted_clf.fit(X_train_prepped, y_train)

n_iterations: 5
n_required_iterations: 5
n_possible_iterations: 7
min_resources_: 20
max_resources_: 34991
aggressive_elimination: False
factor: 3
----------
iter: 0
n_candidates: 192
n_resources: 20
Fitting 5 folds for each of 192 candidates, totalling 960 fits
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=2; total time=   0.0s

C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_search.py:324: UserWarning: The total space of parameters 192 is smaller than n_iter=1749. Running 192 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=0, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=2, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=3, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, reg_alpha=5, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=0, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=2, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=3, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, reg_alpha=5, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=0, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=2, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=3, reg_lambda=5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=5, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=5, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=5, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=5, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=5, reg_lambda=0; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=5, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=5, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=5, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=5, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=5, reg_lambda=2; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=5, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=5, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=5, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=5, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=5, reg_lambda=3; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, reg_alpha=5, reg_lambda=5; total time=   0.0s

HalvingRandomSearchCV(estimator=XGBClassifier(base_score=None, booster=None,
                                              callbacks=None,
                                              colsample_bylevel=None,
                                              colsample_bynode=None,
                                              colsample_bytree=None,
                                              device=None,
                                              early_stopping_rounds=None,
                                              enable_categorical=False,
                                              eval_metric=None,
                                              feature_types=None,
                                              feature_weights=None, gamma=None,
                                              grow_policy=None,
                                              importance_type=None,
                                              interaction_constraints...
                                              max_cat_threshold=None,
                                              max_cat_to_onehot=None,
                                              max_delta_step=None,
                                              max_depth=None, max_leaves=None,
                                              min_child_weight=None,
                                              missing=nan,
                                              monotone_constraints=None,
                                              multi_strategy=None,
                                              n_estimators=None, n_jobs=-1,
                                              num_parallel_tree=None, ...),
                      param_distributions={'learning_rate': [0.01, 0.03, 0.05,
                                                             0.1],
                                           'max_depth': [3, 5, 7],
                                           'reg_alpha': [0, 2, 3, 5],
                                           'reg_lambda': [0, 2, 3, 5]},
                      verbose=2)

In [43]:
best_model = boosted_clf.best_estimator_

best_model_train_score = best_model.score(X_train_prepped, y_train)
best_model_test_score = best_model.score(X_test_prepped, y_test)
 
print(f'train score: {best_model_train_score}')
print(f'test score: {best_model_test_score}')

train score: 0.8172958760824212
test score: 0.8102423411065386

In [45]:
print(boosted_clf.best_params_)

{'reg_lambda': 2, 'reg_alpha': 0, 'max_depth': 3, 'learning_rate': 0.1}